### ISSUE TITLE
Please make the plugin requirement optional.

### ISSUE THREAD

**Issue by Yggdrasil** [aptible/elasticsearch-logstash-s3-backup#14]
Hi, well done. This tool seems perfect for our needs, except that it requires the repository-s3 plugin to be available.

We use Elastic Cloud (https://www.elastic.co/cloud) as our ElasticSearch server and it doesn't allow installing custom plugins unless you're willing to pay for their higher tier support, which is way out of our league.

I have a feature request. Could you please make it possible to use this tool without ES plugins, so using only client-side scripting. I realize it's probably a lot less efficient but it would work, right?

Thanks for your consideration.

**Comment by Yggdrasil** [comment]
To be clear, I understand this app is designed for the Aptible platform so I can totally understand if you say this feature is out of scope. However, since it's very useful in itself it could have much greater reach.

**Comment by krallin** [comment]
Hi there,

As you noted, this app is primarily designed to be used on Aptible; it's unlikely we'll be able to commit engineering effort towards adding support for a use case like yours that wouldn't be relevant for Aptible users.

Good luck with your project!

Cheers,

**Comment by Yggdrasil** [comment]
Thanks @krallin. That's understandable.

Some good news from Elastic.co though. They confirmed the repository-s3 plugin is included in their Cloud clusters, even though it's not listed in the docs. So, I should be able to make your code work after all.

**Comment by krallin** [comment]
Glad to hear this worked out for you :)
